// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PLCCommunication_Infrastructure.DBContexts;

#nullable disable

namespace PLCCommunication_Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250310123328_UpdateModbuConfig")]
    partial class UpdateModbuConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PLCCommunication_Model.Entities.ModbusTCPConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createtime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("FunctionCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("Num")
                        .HasColumnType("int");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("ProxyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("SlaveID")
                        .HasColumnType("tinyint");

                    b.Property<int>("StartAddress")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("T_ModbusTCPConfig", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
